-- MySQL Script generated by MySQL Workbench
-- 04/23/16 22:35:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema citygame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema citygame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citygame` DEFAULT CHARACTER SET utf8 ;
USE `citygame` ;

-- -----------------------------------------------------
-- Table `citygame`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citygame`.`player` ;

CREATE TABLE IF NOT EXISTS `citygame`.`player` (
  `player_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(32) NOT NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`player_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citygame`.`gameobj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citygame`.`gameobj` ;

CREATE TABLE IF NOT EXISTS `citygame`.`gameobj` (
  `gameobj_id` VARCHAR(64) NULL,
  `parent_gameobj_id` VARCHAR(64) NULL,
  `player_id` INT UNSIGNED NULL,
  `object_type` INT UNSIGNED NULL COMMENT '1=Ground\n2=Generated\n3=UserCreated',
  `prefab` VARCHAR(255) NULL,
  `pos_x` DOUBLE NULL,
  `pos_y` DOUBLE NULL,
  `pos_z` DOUBLE NULL,
  `rot_x` DOUBLE NULL,
  `rot_y` DOUBLE NULL,
  `rot_z` DOUBLE NULL,
  `rot_w` DOUBLE NULL,
  `scale_x` DOUBLE NULL,
  `scale_y` DOUBLE NULL,
  `scale_z` DOUBLE NULL,
  `layer` INT UNSIGNED NULL,
  `tag` VARCHAR(64) NULL,
  PRIMARY KEY (`gameobj_id`),
  INDEX `fk_gameobj_player_idx` (`player_id` ASC),
  INDEX `fk_child_go_parent_go_idx` (`parent_gameobj_id` ASC),
  CONSTRAINT `fk_gameobj_player`
    FOREIGN KEY (`player_id`)
    REFERENCES `citygame`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_child_go_parent_go`
    FOREIGN KEY (`parent_gameobj_id`)
    REFERENCES `citygame`.`gameobj` (`gameobj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
