//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityGameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gameobj()
        {
            this.gameobj1 = new HashSet<gameobj>();
        }
    
        public string gameobj_id { get; set; }
        public string parent_gameobj_id { get; set; }
        public Nullable<long> player_id { get; set; }
        public Nullable<long> object_type { get; set; }
        public string prefab { get; set; }
        public Nullable<double> pos_x { get; set; }
        public Nullable<double> pos_y { get; set; }
        public Nullable<double> pos_z { get; set; }
        public Nullable<double> rot_x { get; set; }
        public Nullable<double> rot_y { get; set; }
        public Nullable<double> rot_z { get; set; }
        public Nullable<double> rot_w { get; set; }
        public Nullable<double> scale_x { get; set; }
        public Nullable<double> scale_y { get; set; }
        public Nullable<double> scale_z { get; set; }
        public Nullable<long> layer { get; set; }
        public string tag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gameobj> gameobj1 { get; set; }
        public virtual gameobj gameobj2 { get; set; }
        public virtual player player { get; set; }
    }
}
